using ATMApp.View;

//do not edit this file, except to call BankingView.Run() at the end of Main()

BankingView.Run();

using System;

// Do not edit this file, except to call ATMView.Start() at the end of Main()
public class ATMService
{
    private double accountBalance = 1000.00;
    private double previousTransaction = 0.00;

    public double GetBalance()
    {
        return accountBalance;
    }

    public void AddMoney(double depositValue)
    {
        if (depositValue > 0)
        {
            accountBalance += depositValue;
            previousTransaction = depositValue;
        }
        else
        {
            Console.WriteLine("Invalid deposit amount. Please enter a positive value.");
        }
    }

    public void RemoveMoney(double withdrawValue, out bool isSuccessful)
    {
        isSuccessful = false;

        if (withdrawValue <= 0)
        {
            Console.WriteLine("Invalid withdrawal amount. Please enter a positive value.");
        }
        else if (withdrawValue <= accountBalance)
        {
            accountBalance -= withdrawValue;
            previousTransaction = -withdrawValue;
            isSuccessful = true;
        }
        else
        {
            Console.WriteLine("Withdrawal Failed. Insufficient Balance");
        }
    }

    public void ShowMiniStatement()
    {
        Console.WriteLine("--- Mini Statement ---");
        Console.WriteLine($"Current Balance: P{accountBalance:F2}");
        Console.WriteLine($"Last Transaction Amount: P{previousTransaction:F2}");
    }
}

public class ATMView
{
    public void ShowMenu()
    {
        Console.WriteLine("Mary Flor Gamali");
        Console.WriteLine("=== Simple ATM System ===");
        Console.WriteLine("1: Check Balance");
        Console.WriteLine("2: Deposit Money");
        Console.WriteLine("3: Withdraw Money");
        Console.WriteLine("4: Print Mini Statement");
        Console.WriteLine("5: Exit");
    }

    public void ShowBalance(double balanceValue)
    {
        Console.WriteLine($"Current Balance: P{balanceValue:F2}");
    }

    public double AskDepositAmount()
    {
        Console.WriteLine("Enter Amount to Deposit: ");
        return Convert.ToDouble(Console.ReadLine());
    }

    public double AskWithdrawAmount()
    {
        Console.WriteLine("Enter Amount to Withdraw: ");
        return Convert.ToDouble(Console.ReadLine());
    }

    public void ShowDepositSuccess(double newBalance)
    {
        Console.WriteLine("Deposit Successful!");
        Console.WriteLine($"Updated Balance: P{newBalance:F2}");
    }

    public void ShowInvalidChoice()
    {
        Console.WriteLine("Invalid option selected. Please try again.");
    }

    public void ShowExitMessage()
    {
        Console.WriteLine("Thank you for using the ATM. Goodbye!");
    }

    public void ShowWithdrawSuccess(double newBalance)
    {
        Console.WriteLine("Withdrawal Successful!");
        Console.WriteLine($"Updated Balance: P{newBalance:F2}");
    }
}

class Program
{
    static void Main(string[] args)
    {
        ATMService atmService = new ATMService();
        ATMView atmView = new ATMView();
        bool transactionStatus;

        while (true)
        {
            atmView.ShowMenu();
            Console.WriteLine("Please Select an Option: ");
            int userChoice = Convert.ToInt32(Console.ReadLine());

            switch (userChoice)
            {
                case 1:
                    atmView.ShowBalance(atmService.GetBalance());
                    break;

                case 2:
                    double depositInput = atmView.AskDepositAmount();
                    atmService.AddMoney(depositInput);
                    atmView.ShowDepositSuccess(atmService.GetBalance());
                    break;

                case 3:
                    double withdrawInput = atmView.AskWithdrawAmount();
                    atmService.RemoveMoney(withdrawInput, out transactionStatus);
                    if (transactionStatus)
                    {
                        atmView.ShowWithdrawSuccess(atmService.GetBalance());
                    }
                    break;

                case 4:
                    atmService.ShowMiniStatement();
                    break;

                case 5:
                    atmView.ShowExitMessage();
                    return;

                default:
                    atmView.ShowInvalidChoice();
                    break;
            }
        }
    }
}
